[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 301

[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
